apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubetestapi
  namespace: argocd
spec:
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: kubernetes
    repoURL: 'https://gitlab.com/samples17/kubetestapi.git'
    targetRevision: dev
  project: default
  syncPolicy:
    automated: null